"""some

Revision ID: 85d78cb47e11
Revises: f6aa3c287a5e
Create Date: 2022-12-17 23:04:17.740126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d78cb47e11'
down_revision = 'f6aa3c287a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
