"""Intial Migrations

Revision ID: bd748d4ab1e3
Revises: 601e2793cbfd
Create Date: 2022-12-16 21:59:47.216127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd748d4ab1e3'
down_revision = '601e2793cbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('member')
    op.drop_table('tweet')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isactive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isactive', sa.BOOLEAN(), nullable=True))

    op.create_table('tweet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=75), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('tweet_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
