"""added

Revision ID: f6aa3c287a5e
Revises: 10bf5cfde2f1
Create Date: 2022-12-17 23:00:10.213097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aa3c287a5e'
down_revision = '10bf5cfde2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=20), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
